### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [smcgithub4me/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You had the right instincts on this project and used some good techniques. Take a look at the issues I created as they will help you optimize your code and improve some techniques. Here is a good article with some examples: 
http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by smcgithub4me** [comment]
Thank you
